import {StyleSheet} from 'react-native';
import {CustomColor, device} from '../../ults';
import {AppColors} from '../../../colors';

export const NhapCuonlStyle = StyleSheet.create({
  inventory: {
    width: device.width,
    height: device.height,
  },
  header: {
    width: '100%',
    height: 'auto',
  },
  headerLine: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    width: '100%',
  },
  headerRef: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'center',
    padding: 5,
    width: '100%',
  },
  headerButton: {
    backgroundColor: AppColors.primary,
    borderRadius: 10,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupHeaderItem: {
    width: '100%',
    display: 'flex',
    // flexDirection: 'column'
  },
  headerText: {
    fontSize: 15,
  },
  headerQrScan: {
    margin: 10,
    padding: 10,
    // width: '20%',
    height: 50,
    backgroundColor: AppColors.primary,
    display: 'flex',
    alignContent: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  accordinsView: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
  },
  inputViewAccordions: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  inputAccordins: {
    width: '80%',
    borderWidth: 1,
    borderColor: CustomColor.colorList.grey,
    borderRadius: 8,
    height: 40,
  },
  pressableAccordins: {
    width: '18%',
    backgroundColor: AppColors.primary,
    height: '100%',
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  desInput: {
    width: 250,
    borderWidth: 1,
    borderColor: CustomColor.colorList.grey,
    borderRadius: 8,
    padding: 5,
    height: 45,
    maxHeight: 50,
    marginRight: 5,
  },
  warehouseView: {
    display: 'flex',
    // width: '100%',
    // height: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 5,
    // marginLeft: 10
  },
  textWarehouseView: {
    width: 80,
    fontSize: 15,
  },
  warehousePressible: {
    borderWidth: 1,
    borderColor: CustomColor.colorList.grey,
    borderRadius: 8,
    height: 45,
    width: 275,
    alignSelf: 'flex-end',
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowTable: {
    borderRadius: 5,
    width: '100%',
    height: 50,
    backgroundColor: CustomColor.colorList.shadowPurple,
    marginBottom: 5,
    // padding: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerCell: {
    alignItems: 'center',
  },
  viewTable: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'black'
  },
  table: {
    width: device.width * 0.99,
    // height: device.height * 0.8,
    padding: 5,
    // borderWidth: 1,
    // borderColor: 'black'
  },
  headerTable: {
    width: 'auto',
    display: 'flex',
    flexDirection: 'row',
    padding: 2,
    marginBottom: 1,
    justifyContent: 'space-between',
    backgroundColor: CustomColor.colorList.shadowBlue,
    borderColor: AppColors.primary,
    borderWidth: 1,
    borderRadius: 5,
    height: 45,
    alignItems: 'center',
  },
  buttonScan: {
    height: 45,
    width: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    borderRadius: 5,
    backgroundColor: AppColors.primary,
  },
  oneLine: {
    display: 'flex',
    flexDirection: 'row',
    // width: "100%"
  },
  pressableIcon: {
    backgroundColor: AppColors.primary,
    padding: 10,
    borderRadius: 10,
    marginRight: 5,
  },
  textInputWithButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: CustomColor.colorList.grey,
    borderRadius: 8,
    height: 45,
    width: 275,
  },
  iconPressable: {
    width: 45,
    height: 45,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: CustomColor.colorList.grey,
  },
});
