export type BoxInfoTypeFromResponse = {
    id?: number,
    ngayTao: Date,
    soCT?: string,
    maQR?: string,
    lines: BoxInfoLineType[],
};
export type BoxInfoLineType = {
    id?: number,
    idHeader?: number,
    ten: string,
    soLo: string,
    slmd: number,
    slM2: number,
    slKgNet: number,
    slKgGross: number,
    ngaySX: Date,
    maySX: string,
    caSX: string,
    lsx: string,
    tenKH: string,
    maTP: string,
    slgd: number,
    maKH: string,
    soQRCode: string,
};